fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    alternatives: "https://github.com/puppet-community/puppet-alternatives"
  symlinks:
    postfix: "#{source_dir}"

